import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import '@/styles/layout/header.scss';
import '@/styles/layout/footer.scss'


import { ReactNode } from 'react';
import { cn } from '@/utils/helpers';
import "bootstrap/dist/css/bootstrap.min.css";
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { ReduxProvider } from '@/redux/Provider';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ProgressProvider from '@/app/ProgressProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'en_US',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
        )}
      >
        <ToastContainer position="top-right" />
        <ReduxProvider>
          <ProgressProvider>
            <Header />
            {children}
            <Footer />
          </ProgressProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
